name: Main Pipeline

# Triggers
on:
  push:
    branches:
      - main
    paths:
      - '**/*.py'
    paths-ignore:
      - 'tests/'
  pull_request:
    branches:
      - main
    paths:
      - '**/*.py'
    paths-ignore:
    - 'tests/'

# Jobs
jobs:
  # TEST
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      # CHECKOUT
      - uses: actions/checkout@v3

      # PYTHON SETUP
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # DEPENDENCIES
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dependencies.txt

      # TEST
      - name: Run Tests
        run: pytest tests/

      # LINT
      - name: Lint Code
        run: |
          pip install pylint
          pylint *.py

  # BUILD
  build-and-deploy:
    needs: test-and-lint
    runs-on: ubuntu-latest
    steps:
      # CHECKOUT
      - uses: actions/checkout@v3

      # LOGIN
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # BUILD AND PUSH
      - name: Build and Push Docker Image
        run: |
          docker build -t prototype:latest .
          docker tag prototype:latest tmozz/prototype:latest
          docker push tmozz/prototype:latest
      # DEPLOY
      - name: Deploy to AWS ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: esc-task.json
          service: INSERT
          cluster: INSERT
          region: 
