name: Main Pipeline

# Triggers
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Jobs
jobs:
  # TEST
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      # CHECKOUT
      - uses: actions/checkout@v3

      # PYTHON SETUP
      - name: py setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

        # DEPENDENCIES
      - name: dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # TEST
      - name: run tests
        run: pytest tests/

      # LINT
      - name: lint
        run: |
          pip install pylint
          pylint *.py

  # BUILD
  build-and-deploy:
    needs: test-and-lint
    runs-on: ubuntu-latest
    steps:
      # CHECKOUT
      - uses: actions/checkout@v3

      # LOGIN
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # BUILD AND PUSH
      - name: build and push
        run: |
        docker build -t prototype:latest .
        docker tag myapp:latest username/prototype:latest
        docker push username/prototype:latest

      # DEPLOY TO AWS
      - uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ecs-task.json # LOOK AT
          service: my-service
          cluster: my-cluster
          region: us-east-1
  
