name: Main Pipeline

# Triggers
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Jobs
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install -r dependencies.txt
      - run: pytest
      
  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: |
        docker build -t myapp:latest .
        docker tag myapp:latest <INSETR_DOCKER_USERNAME>/myapp:latest
        docker push <INSERT_DOCKER_USERNAME>/myapp:latest
      - uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ecs-task.json # LOOK AT
          service: my-service
          cluster: my-cluster
          region: # ENTER REGION
  
